Script started on 2020-10-22 16:59:18-06:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="168" LINES="14"]
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ exit./difference gcc -g -Wall difference.c -o difference -lm
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ gcc -g -Wall difference.c -o difference -lm[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cexit[K./difference 
The difference between the sum of the squares and the square of the sum from 1 to 100 is 25164150
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ exit
exit

Script done on 2020-10-22 16:59:45-06:00 [COMMAND_EXIT_CODE="0"]
