Script started on 2020-10-21 22:19:57-06:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="168" LINES="14"]
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ gcc -g -Wall -c zopm[K[Kmbie.c
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ gcc -g -Wall zombie.o zom[K[K[Klab6.c -o lab6
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ ./lab6

1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
>> 1

Was this zombie found dead? Y or N
>> Y

Please enter the number of toes the zombie has.
>> 14

Please choose the day this zombie was encountered.
1) Monday
2) Tuesday
3) Wednesday
4) Thursday
5) Friday
6) Saturday
7) Sunday
>> 4

Enter the time this zombie was encountered.
Separate hours, minutes, and seconds by colons.
HH:MM:SS
>> 12:34:23  56

1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
>> 2

1. This zombie was found dead.
This zombie had 14 toes.
This zombie was sighted Thursday at 12:34:56

1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
>> 1

Was this zombie found dead? Y or N
>> N

Please enter the amount of blood that oozed from its body.
>> 54.6

Please choose the day this zombie was encountered.
1) Monday
2) Tuesday
3) Wednesday
4) Thursday
5) Friday
6) Saturday
7) Sunday
>> 2

Enter the time this zombie was encountered.
Separate hours, minutes, and seconds by colons.
HH:MM:SS
>> 6:23:16

1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
>> 2

1. This zombie was found dead.
This zombie had 14 toes.
This zombie was sighted Thursday at 12:34:56

2. This zombie was found ALVIE!
It was drained of 54.599998 mL of blood once killed.
This zombie was sighted Tuesday at 6:23:16

1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
>> 1

Was this zombie found dead? Y or N
>> N

Please enter the amount of blood that oozed from its body.
>> 34.23

Please choose the day this zombie was encountered.
1) Monday
2) Tuesday
3) Wednesday
4) Thursday
5) Friday
6) Saturday
7) Sunday
>> 7

Enter the time this zombie was encountered.
Separate hours, minutes, and seconds by colons.
HH:MM:SS
>> 3:24:34: 

1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
>> 2 1

Was this zombie found dead? Y or N
>> Y

Please enter the number of toes the zombie has.
>> 123 

Please choose the day this zombie was encountered.
1) Monday
2) Tuesday
3) Wednesday
4) Thursday
5) Friday
6) Saturday
7) Sunday
>> 5

Enter the time this zombie was encountered.
Separate hours, minutes, and seconds by colons.
HH:MM:SS
>> 7:43:45

1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
>> 1

Was this zombie found dead? Y or N
>> N

Please enter the amount of blood that oozed from its body.
>> 54.7

Please choose the day this zombie was encountered.
1) Monday
2) Tuesday
3) Wednesday
4) Thursday
5) Friday
6) Saturday
7) Sunday
>> 4

Enter the time this zombie was encountered.
Separate hours, minutes, and seconds by colons.
HH:MM:SS
>> $ 45:23:12

1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
>> 1

Was this zombie found dead? Y or N
>> Y

Please enter the number of toes the zombie has.
>> 0

Please choose the day this zombie was encountered.
1) Monday
2) Tuesday
3) Wednesday
4) Thursday
5) Friday
6) Saturday
7) Sunday
>> 1

Enter the time this zombie was encountered.
Separate hours, minutes, and seconds by colons.
HH:MM:SS
>> 00:00:00

1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
>> 2

1. This zombie was found dead.
This zombie had 0 toes.
This zombie was sighted Monday at 0:0:0

2. This zombie was found ALVIE!
It was drained of 54.599998 mL of blood once killed.
This zombie was sighted Tuesday at 6:23:16

3. This zombie was found ALVIE!
It was drained of 34.230000 mL of blood once killed.
This zombie was sighted Sunday at 3:24:34

4. This zombie was found dead.
This zombie had 12 toes.
This zombie was sighted Friday at 7:43:45

5. This zombie was found ALVIE!
It was drained of 54.700001 mL of blood once killed.
This zombie was sighted Thursday at 45:23:12

1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
>> 3

Stay alert! Keep a watch out for zombies!!

GOODBYE and GOOD LUCK!
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ exit
exit

Script done on 2020-10-21 22:23:42-06:00 [COMMAND_EXIT_CODE="1"]
