Script started on 2020-10-22 16:48:27-06:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="168" LINES="14"]
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ exitgcc -g -Wal smallest.c -o smallest[1@l
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ gcc -g -Wall smallest.c -o smallestexit[Kgcc -g -Wal smallest.c -o smallestexit[Kgcc -g -Wall smallest.c -o smallest[K./smallest 
The smallest number that can be divided by each number from 1 to 20 is 232792560
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ exit
exit

Script done on 2020-10-22 16:48:48-06:00 [COMMAND_EXIT_CODE="1"]
