Script started on 2020-10-22 17:19:03-06:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="168" LINES="14"]
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ gcc -g -Wall sundays.c -o sundays
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ ./s[Ksundays 
Number of sundays that fell on the first of the month between 1901 and 2000: 171
]0;dxgriego@Parallels: ~/cse113/lab6[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab6[00m$ exit
exit

Script done on 2020-10-22 17:19:24-06:00 [COMMAND_EXIT_CODE="0"]
